config/routes.rb
Rails.application.routes.draw do
  resources :blogs

  #user routing
  resource :users, only: [:create]
  get '/users/sign_up', to: 'users#new', as: 'new_user'
  get '/mypage/:id', to: 'users#show', as: 'user'
  patch '/mypage/:id', to: 'users#update'
  put '/mypage/:id', to: 'users#update'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'

  #Login routing
  get '/users/sign_in', to: 'sessions#new', as: 'new_sessions'
  post   '/users/sign_in', to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as: 'delete_sessions'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, length: { in: 1..30 }
  validates :content, length: { in: 1..255 }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  #アソシエーション
  has_many :blogs

  #secure password
  has_secure_password

  #validation
  before_validation { email.downcase! }
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true,  uniqueness: true, length: {maximum: 255},format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password,presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i(show edit update destroy)

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        redirect_to blogs_path, notice: "ブログを投稿しました"
      else
        render :new
      end
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました"
  end

  private
  def set_blog
    @blog = current_user.blogs.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to  user_path(user.id),notice:'ログインしました'
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'ログアウトしました'
    render 'new'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :user_find, only: [:show,:edit,:update]

  def new
     @user = User.new
  end

  def create
    @user= User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "会員登録が完了しました。"
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  #アップデートアクション
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "会員情報を変更しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def user_find
    @user= User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面へ", blogs_path %>

app/views/blogs/edit.html.erb
<h2>ブログを編集する</h2>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>
<table>
  <tr>
    <th>タイトル</th>
    <th>コンテンツ</th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.title %></td>
      <td><%= blog.content %></td>
      <td><%= link_to '詳細確認', blog_path(blog.id) %></td>
      <td><%= link_to "編集", edit_blog_path(blog.id) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'ブログ投稿画面へ', new_blog_path %>

app/views/blogs/new.html.erb
<h2>ブログを投稿する</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>ブログ詳細画面</h1>
<p>タイトル: <%= @blog.title %></p>
<p>コンテンツ: <%= @blog.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DicDay10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="header clearfix">
      <div class="title clearfix">Blog App</div>
      <div class="header-menu clearfix">
      <ul class="header-ul clearfix">
      <% if current_user %>
        <li class="header-item clearfix"><%= link_to current_user.name,"/mypage/#{current_user.id}" %></li>
        <li class="header-item clearfix"><%= link_to 'ブログ一覧', '/blogs' %></li>
        <li class="header-item clearfix"><%= link_to 'ログアウト', '/logout',method: :delete %></li>
      <% else %>
        <li class="header-item clearfix"><%= link_to '新規登録', '/users/sign_up' %></li>
        <li class="header-item clearfix"><%= link_to 'ログイン', '/users/sign_in' %></li>
      <% end %>
      </ul>
      </div>
  </div>

  <% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
  <% end %>

  <div class="main">
    <%= yield %>
  </div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

   <div>
     <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <%= form.submit %>
<% end %>

app/views/users/edit.html.erb
  <h4>会員情報編集</h4>

  <%= render 'form' %>

  <%= link_to '戻る', user_path(@user) %>

app/views/users/new.html.erb
<h4>新規登録</h4>

<%= render 'form' %>

app/views/users/show.html.erb
<h4>ユーザ情報</h4>

  <label>ユーザ名</label>
  <p><%= @user.name %></p>

  <label>Eメール</label>
  <p><%= @user.email %></p>

  <%= link_to '編集', edit_user_path(@user) %>